source 'http://rubygems.org'
source 'http://gems.github.com'

gem 'rails', '2.3.5'
gem 'haml', '2.2.23'
gem 'sqlite3'
gem 'compass'
gem 'authlogic'
gem 'authlogic-oid'
gem 'inherited_resources', '=1.0.3'
gem 'will_paginate'
gem 'formtastic'
gem 'googlecharts'
gem 'facebooker', '1.0.67'
gem 'ruby-openid',  '>= 2.0.4'
gem 'mysql'
gem 'authlogic-connect'

group :test do
  gem 'rspec',  '~> 1.3.1'
  gem 'rspec-rails',  '~> 1.3.3'
  gem 'shoulda',  '~> 2.10.3'
  gem 'machinist',  '~> 1.0.6'
  gem 'faker',  '= 0.3.1'
  gem 'capybara', '0.3.9'
  gem 'launchy'
end
